import React, { useState, useEffect } from "react";
import { Terminal, Search, ShieldAlert, Database, FileText } from "lucide-react";
import { SystemEvent } from "../types";

export const LogsTab: React.FC = () => {
  const [selectedFile, setSelectedFile] = useState<string>("trading.log");
  const [availableFiles, setAvailableFiles] = useState<string[]>([]);
  const [logLines, setLogLines] = useState<string[]>([]);
  const [systemEvents, setSystemEvents] = useState<SystemEvent[]>([]);
  const [filterQuery, setFilterQuery] = useState<string>("");
  const [linesCount, setLinesCount] = useState<number>(200);

  useEffect(() => {
    fetch(`/api/logs?file=${selectedFile}`)
      .then((res) => res.json())
      .then((data) => {
        setAvailableFiles(data.availableFiles || []);
        setLogLines(data.lines || []);
        setSystemEvents(data.systemEvents || []);
      })
      .catch((err) => console.error(err));
  }, [selectedFile]);

  const filteredLogs = logLines.filter((line) =>
    line.toLowerCase().includes(filterQuery.toLowerCase())
  );

  return (
    <div className="space-y-6">
      {/* File Viewer Card */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 shadow-sm">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-4">
          <div>
            <h3 className="text-sm font-semibold text-white flex items-center gap-2">
              <Terminal className="w-4 h-4 text-emerald-400" />
              Application Rotating Log File Inspector
            </h3>
            <p className="text-xs text-slate-400">
              Inspect live rotating log streams generated by daemon, API wrapper, and ML engine
            </p>
          </div>

          <div className="flex items-center gap-3">
            <select
              value={selectedFile}
              onChange={(e) => setSelectedFile(e.target.value)}
              className="bg-slate-800 border border-slate-700 text-white text-xs rounded-lg px-3 py-1.5 focus:outline-none focus:border-emerald-500 font-mono"
            >
              {availableFiles.map((f) => (
                <option key={f} value={f}>
                  {f}
                </option>
              ))}
            </select>

            <div className="relative w-48">
              <Search className="w-3.5 h-3.5 text-slate-500 absolute left-2.5 top-2.5" />
              <input
                type="text"
                placeholder="Filter lines..."
                value={filterQuery}
                onChange={(e) => setFilterQuery(e.target.value)}
                className="w-full bg-slate-800 border border-slate-700 text-xs text-slate-200 rounded-lg pl-8 pr-2 py-1.5 focus:outline-none focus:border-emerald-500"
              />
            </div>
          </div>
        </div>

        {/* Console / Terminal Output Box */}
        <div className="bg-slate-950 border border-slate-800 rounded-lg p-4 font-mono text-xs text-slate-300 max-h-80 overflow-y-auto space-y-1 select-text">
          {filteredLogs.length === 0 ? (
            <p className="text-slate-500 italic">No matching log lines found.</p>
          ) : (
            filteredLogs.slice(-linesCount).map((line, idx) => (
              <div key={idx} className="leading-relaxed hover:bg-slate-900/60 px-1 rounded">
                {line.includes("[ERROR]") ? (
                  <span className="text-rose-400">{line}</span>
                ) : line.includes("[WARNING]") ? (
                  <span className="text-amber-300">{line}</span>
                ) : line.includes("Signal") || line.includes("ORDER") ? (
                  <span className="text-emerald-400 font-semibold">{line}</span>
                ) : (
                  <span className="text-slate-300">{line}</span>
                )}
              </div>
            ))
          )}
        </div>
      </div>

      {/* DB System Events */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 shadow-sm">
        <h3 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
          <Database className="w-4 h-4 text-teal-400" />
          System Events Database Table
        </h3>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-800/80 text-slate-400 font-medium uppercase tracking-wider">
              <tr>
                <th className="py-2.5 px-4 rounded-l-lg">Timestamp</th>
                <th className="py-2.5 px-4">Level</th>
                <th className="py-2.5 px-4">Component</th>
                <th className="py-2.5 px-4 rounded-r-lg">Event Message</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800 text-slate-200">
              {systemEvents.map((evt) => (
                <tr key={evt.id} className="hover:bg-slate-800/40">
                  <td className="py-2.5 px-4 text-slate-400 font-mono text-[11px]">
                    {new Date(evt.timestamp).toLocaleString("en-IN")}
                  </td>
                  <td className="py-2.5 px-4">
                    <span
                      className={`px-2 py-0.5 rounded font-bold text-[10px] ${
                        evt.level === "ERROR"
                          ? "bg-rose-500/20 text-rose-300"
                          : evt.level === "WARNING"
                          ? "bg-amber-500/20 text-amber-300"
                          : "bg-teal-500/20 text-teal-300"
                      }`}
                    >
                      {evt.level}
                    </span>
                  </td>
                  <td className="py-2.5 px-4 font-mono text-slate-300">{evt.component}</td>
                  <td className="py-2.5 px-4 text-white font-medium">{evt.message}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
